language: node_js
node_js:
  - "8"

before_install:
    - yarn init -y
    - yarn global add greenkeeper-lockfile@1
before_script: ./scripts/greenkeeper-update.sh
after_script: ./scripts/greenkeeper-upload.sh

services:
    - docker

jobs:
    include:
        - stage: spec tests
          script: ./scripts/spec-test-server.sh
        - script: ./scripts/spec-test-widgets.sh
        - stage: deploy widget documentation
          script: ./scripts/deploy-widgets.sh
        - deploy:
              provider: npm
              email: $NPM_EMAIL_ADDRESS
              api_key: $NPM_API_KEY
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c8d311cf741ea64d3faf
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
