language: node_js
node_js:
  - "8"

before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

services:
    - docker

jobs:
    include:
        - stage: server spec tests
          script:
              - cd /server
              - yarn lint
              - yarn test:ci
        - stage: widget spec tests
          script:
              - cd /widgets
              - yarn lint
        - stage: deploy widget documentation
          script:
              - cd /widgets
              - yarn deploy-docs
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f71d5842154b57a009fd
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
