language: node_js
node_js:
- '8'
before_install:
- yarn init -y
- yarn global add greenkeeper-lockfile@1
before_script: "./scripts/greenkeeper-update.sh"
after_script: "./scripts/greenkeeper-upload.sh"
jobs:
  include:
  - stage: Spec Tests
    script: "./scripts/spec-test-server.sh"
  - script: "./scripts/spec-test-widgets.sh"
  - stage: Deploy Widgets
    script: "./scripts/deploy-widgets.sh"
    before_deploy: cd $TRAVIS_BUILD_DIR/widgets
    deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key:
            secure: $NPM_API_KEY
        skip_cleanup: true
        on:
            branch: master
            node: '8'
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/c8d311cf741ea64d3faf
    on_success: change
    on_failure: always
    on_start: never
