language: node_js
node_js:
  - "8"

before_install:
    - cd /server
    - yarn global add greenkeeper-lockfile@1
    - cd ../widgets
    - yarn global add greenkeeper-lockfile@1
before_script:
    - cd /server
    - greenkeeper-lockfile-update
    - cd ../widgets
    - greenkeeper-lockfile-update
after_script:
    - cd /server
    - greenkeeper-lockfile-upload
    - cd ../widgets
    - greenkeeper-lockfile-upload

services:
    - docker

jobs:
    include:
        - stage: spec tests
          script: ./scripts/spec-test-server.sh
        - script: ./scripts/spec-test-widgets.sh
        - stage: deploy widget documentation
          script: ./scripts/deploy-widgets.sh
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f71d5842154b57a009fd
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
